server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.ljw.shop.pojo
  config-location: classpath:/config/mybatis-config.xml
logging:
  file:
    name: slf4j-BootShop
    path: ./logs
    max-size: 20MB
    max-history: 7
  level:
    root: info
    cn.ljw.shop.mapper: debug
  config: classpath:logback-spring.xml

spring:
  datasource:
    #Mysql 5
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3307/bootshop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
  redis:
    host: 127.0.0.1

#  mvc:
#    pathmatch:
# 接口文档
springdoc:
  packages-to-scan: cn.ljw.shop.controller
  swagger-ui:
    enabled: true

