server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.ljw.shop.pojo
  config-location: classpath:/config/mybatis-config.xml

logging:
  level:
    sql: debug
spring:
  datasource:
    #Mysql 5
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3307/bootshop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
  redis:
    host: 127.0.0.1

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher